### ISSUE TITLE
Formalise packet structure

### ISSUE THREAD

**Issue by juzsal** [CosmicPi/cosmicpi-arduino#1]
The structure of packets sent by the firmware needs to be formalised. This is for several reasons: 
- To have a quick reference for ourselves (and for others) without having to dig into the code.
- To allow unit testing.
- To allow versioning of the protocol over different iterations of hardware and software.
### What packets do we send?

There appears to be 10 distinct packet types currently sent by the firmware, which we can formalise for `v1`:
1. Temperature sensor readout
2. Barometric sensor readout
3. Vibration sensor readout
4. Magnetic field strength
5. Accelerometer
6. GPS
7. Timing information
8. Statuses of the various chips
9. ADC readout
10. Power status
### Discussion points:
- Do we need all these packets?
- Do we need more packets?
- Can we combine some of them?
### Temperature sensor readout:

``` json

```

**Comment by quixoft** [comment]
There is no reason to do orientation calculation on the due, so that in the client, the due has limited resources and there is simply no need when it's so simple to perform the calculation in python.

**Comment by quixoft** [comment]
The format should be easily readable ascii because there are no bandwidth issues on the Arduino, it's easily displayed and simple. Binary leads to enormous problems with big integers, floating point. I see no advantage at all and a lot of problems. I have already had problems with my first version and time_t values between 32 and 64 bit systems. Strongly advise avoid binary.

**Comment by quixoft** [comment]
So let's take the format I have already described I detail and use that. It's already there, it works. If we need some more fields, then we can agree to add them as needed.

**Comment by quixoft** [comment]
So take the first 100 line comment in the Arduino code and call it the spec

**Comment by juzsal** [comment]
@quixoft ok, so we can remove packets 5 and 7, right?

If you feel strongly against the binary format, then let's go with the JSON approach. By the way, the [struct library](https://docs.python.org/2/library/struct.html) provides built-in support for converting binary strings in a platform-independent way (James and I already implemented it, it's relatively simple).

If we aren't worried about bandwidth, then I suggest we rename the identifiers to be more human-readable.

``` json
{'STS':{'Qsz':i,'Mis':i,'Ter':i,'Htu':i,'Bmp':i,'Acl':i,'Mag':i}}
```

At a quick glance I don't know that these fields are. How about something like this (similar for the other packets):

``` json
{ "status": 
  { 
    "queue_size": 0, 
    "missed_events": 0, 
    "buffer_error": 0, 
    "temp_status": 0,
    "baro_status": 0,
    "accel_status": 0,
    "mag_status": 0, 
}
```

**Comment by quixoft** [comment]
Good, agreed. And it's not easy to just convert to network format. Even in
the code we have there are some nasty 32/64 bit issues, and python supports
integers that can be thousands of digits long. If you look at the date time
in the Arduino it's a single integer of 12 digits, try converting that into
binary ! So we agree, long names are ok. I just like all my field names to
be short and the same length...It's a matter of taste, I don't have a
problem using ragged dictionaries in python even if it does make name
lookup longer and hashing difficult. Just remember there is a price to pay
at run time using long names.

On Mon, May 9, 2016, 20:40 Justin Lewis Salmon notifications@github.com
wrote:

> @quixoft https://github.com/quixoft ok, so we can remove packets 5 and
> 7, right?
> 
> If you feel strongly against the binary format, then let's go with the
> JSON approach. By the way, the struct library
> https://docs.python.org/2/library/struct.html provides built-in support
> for converting binary strings in a platform-independent way (James and I
> already implemented it, it's relatively simple).
> 
> If we aren't worried about bandwidth, then I suggest we rename the
> identifiers to be more human-readable.
> 
> {'STS':{'Qsz':i,'Mis':i,'Ter':i,'Htu':i,'Bmp':i,'Acl':i,'Mag':i}}
> 
> At a quick glance I don't know that these fields are. How about something
> like this:
> 
> { "status":
>   {
>     "queue_size": 0,
>     "missed_events": 0,
>     "buffer_error": 0,
>     "temp_status": 0,
>     "baro_status": 0,
>     "accel_status": 0,
>     "mag_status": 0,
> }
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/1#issuecomment-217951292
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by quixoft** [comment]
By the way take a look at the code in the python server/client and replace
all the short strings by long names...

On Mon, May 9, 2016, 20:51 Julian Lewis lewis.julian@gmail.com wrote:

> Good, agreed. And it's not easy to just convert to network format. Even in
> the code we have there are some nasty 32/64 bit issues, and python supports
> integers that can be thousands of digits long. If you look at the date time
> in the Arduino it's a single integer of 12 digits, try converting that into
> binary ! So we agree, long names are ok. I just like all my field names to
> be short and the same length...It's a matter of taste, I don't have a
> problem using ragged dictionaries in python even if it does make name
> lookup longer and hashing difficult. Just remember there is a price to pay
> at run time using long names.
> 
> On Mon, May 9, 2016, 20:40 Justin Lewis Salmon notifications@github.com
> wrote:
> 
> > @quixoft https://github.com/quixoft ok, so we can remove packets 5 and
> > 7, right?
> > 
> > If you feel strongly against the binary format, then let's go with the
> > JSON approach. By the way, the struct library
> > https://docs.python.org/2/library/struct.html provides built-in
> > support for converting binary strings in a platform-independent way (James
> > and I already implemented it, it's relatively simple).
> > 
> > If we aren't worried about bandwidth, then I suggest we rename the
> > identifiers to be more human-readable.
> > 
> > {'STS':{'Qsz':i,'Mis':i,'Ter':i,'Htu':i,'Bmp':i,'Acl':i,'Mag':i}}
> > 
> > At a quick glance I don't know that these fields are. How about something
> > like this:
> > 
> > { "status":
> >   {
> >     "queue_size": 0,
> >     "missed_events": 0,
> >     "buffer_error": 0,
> >     "temp_status": 0,
> >     "baro_status": 0,
> >     "accel_status": 0,
> >     "mag_status": 0,
> > }
> > 
> > —
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/CosmicPi/cosmicpi-arduino/issues/1#issuecomment-217951292
> > 
> > ## 
> 
> Julian Lewis
> Mobile: +33646447515
> 
> ## 

Julian Lewis
Mobile: +33646447515
