### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by juzsal** [CosmicPi/cosmicpi-arduino#2]
The standard [fork/pull model](https://help.github.com/articles/using-pull-requests/) should be used to contribute code to the official CosmicPi repos.

This allows contributors to work on their own repositories and make a pull request to the official repo for team review once it's been tested.

Everyone in the team should sign off a PR before it gets merged.

**Comment by quixoft** [comment]
Sure, I am not sure we are talking about the same thing. I don't know what
work flow you want. You can obviously do your own thing, make your own
branch and do what you want, but you can't merge that back into the master
without first having your code reviewed by the rest of the team.  To do
that you must generate patches we can look at, then of all of ok, they get
applied. The Linux work flow is way over the top, are you suggesting we
start working with branch mergers ? That is a difficult model to manage.

On Mon, May 9, 2016, 20:07 Justin Lewis Salmon notifications@github.com
wrote:

> The fork/pull model
> https://help.github.com/articles/using-pull-requests/ should be used to
> contribute code to the official CosmicPi repos.
> 
> This allows contributors to work on their own repositories and make a pull
> request to the official repo for team review once it's been tested.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
@quixoft yes, that's the whole point of the fork/pull model, to allow someone to work privately on their own copy of the code and then ask for it to be merged into the official repo. Fork the repo, make some changes, submit a PR. It's all explained in the link above.

Somebody has to merge the patch once everyone agrees. I am very used to doing this, I do it on a daily basis, so I am happy to take the merge responsibility.

**Comment by quixoft** [comment]
I am not convinced that is the best model. I guess that is because I am used to the Linux kernel workflow. I would prefer to keep my own repository on my computer, and submit patches. I own the Arduino code and if you want to change it, send me a patch.

**Comment by juzsal** [comment]
The linux kernel workflow **is** the fork/pull model. https://github.com/torvalds/linux has 12,000 forks and currently 93 pull requests. PR == patch.

**Comment by quixoft** [comment]
Then it's completely over the top for our needs

On Mon, May 9, 2016, 20:47 Justin Lewis Salmon notifications@github.com
wrote:

> The linux kernel workflow _is_ the fork/pull model.
> https://github.com/torvalds/linux has 12,000 forks and currently 93 pull
> requests. PR == patch.
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217953375
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
No it isn't, it's what literally every project on GitHub does that has more than one contributor. It has been specifically designed for that, so that people don't have to send each other patches by email any more. It is one of the main reasons why GitHub is so popular. How else would you suggest?

**Comment by quixoft** [comment]
In the link you sent me, it describes a method for working on archives located on Git hub. The Linux work flow is described in the progit book. So we are talking at cross purposes. That is not the work flow I used

**Comment by quixoft** [comment]
Send patches using Git send email, it's what I habe used, it's simple, and
there are not thousands of us working on the pi project. We don't need that
level of complexity when there are only 3 of us. Email is fine I'd it's
limited to a few.

On Mon, May 9, 2016, 21:00 Justin Lewis Salmon notifications@github.com
wrote:

> No it isn't, it's what literally every project on GitHub does that has
> more than one contributor. It has been specifically designed for that, so
> that people don't have to send each other patches by email any more. It is
> one of the main reasons why GitHub is so popular. How else would you
> suggest?
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217956927
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
The GitHub PR mechanism is much, much easier and less complex than sending patches by email like it's 1995. That's why it's there.

**Comment by quixoft** [comment]
Well be blunt, I haven't used it, so I am willing to go with your advise. I
have never been comfortable with Git branches and have ended up in a
horrible mess on numerous occasions. Our Git guru spent huge amounts of his
time maintaining our tree. I am trying to keep a small project simple, so
you win if its genuinely easier than just sending a patch. That certainly
isn't complicated,  clone the repo, make my own branch and do what I want,
mean while get pushes from the orig master,  finally generate my patches,
get them reviewed, and merge to get them applied. Yes it involves getting
the patches by email so that they get reviewed. They are always small and
easy to read.

On Mon, May 9, 2016, 21:09 Justin Lewis Salmon notifications@github.com
wrote:

> I'm sorry to be blunt Julian, but GitHub PR mechanism is much, much easier
> and less complex than sending patches by email like it's 1995. That's why
> it's there.
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217959532
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
We're talking about pretty much exactly the same thing, just using a web interface to send the patches and do the review rather than using email. Please give it a go, you'll see how easy it is. (You don't have to branch on your personal repo if you don't want to.)

I realised I should have sent you [this link which shows how to fork a repo](https://help.github.com/articles/fork-a-repo/) before you can create a pull request.

**Comment by quixoft** [comment]
Ok I will give it a go

On Mon, May 9, 2016, 21:34 Justin Lewis Salmon notifications@github.com
wrote:

> We're talking about pretty much exactly the same thing, just using a web
> interface to send the patches and do the review rather than using email.
> Please give it a go, you'll see how easy it is. (You don't have to branch
> on your personal repo if you don't want to.)
> 
> I realised I should have sent you this link which shows how to fork a repo
> https://help.github.com/articles/fork-a-repo/ before you can create a
> pull request.
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217965692
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
I made a pull request to show you how it works: https://github.com/CosmicPi/cosmicpi-daq/pull/1

Everyone can see the diff of the commit I made and make comments on it. If something looks wrong or missing, I can add further commits to the PR. It even tells you automatically if it can be merged without conflict - it's pretty cool!

**Comment by quixoft** [comment]
Yes that was easy, and I just made a comment about the implication of
simulated events on the server. You are correct it was very easy

On Mon, May 9, 2016, 21:49 Justin Lewis Salmon notifications@github.com
wrote:

> I made a pull request to show you how it works: CosmicPi/cosmicpi-daq#1
> https://github.com/CosmicPi/cosmicpi-daq/pull/1
> 
> Everyone can see the diff of the commit I made and make comments on it. If
> something looks wrong or missing, I can add further commits to the PR. It
> even tells you automatically if it can be merged without conflict - it's
> pretty cool!
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217969247
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by quixoft** [comment]
I am doing this all on my phone, no way I could have done that without a
web interface.

On Mon, May 9, 2016, 21:57 Julian Lewis lewis.julian@gmail.com wrote:

> Yes that was easy, and I just made a comment about the implication of
> simulated events on the server. You are correct it was very easy
> 
> On Mon, May 9, 2016, 21:49 Justin Lewis Salmon notifications@github.com
> wrote:
> 
> > I made a pull request to show you how it works: CosmicPi/cosmicpi-daq#1
> > https://github.com/CosmicPi/cosmicpi-daq/pull/1
> > 
> > Everyone can see the diff of the commit I made and make comments on it.
> > If something looks wrong or missing, I can add further commits to the PR.
> > It even tells you automatically if it can be merged without conflict - it's
> > pretty cool!
> > 
> > —
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/CosmicPi/cosmicpi-arduino/issues/2#issuecomment-217969247
> > 
> > ## 
> 
> Julian Lewis
> Mobile: +33646447515
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by juzsal** [comment]
Great, I'm glad it was easy :)

By the way, is there any way you can get your mobile mail client to not include the text of the original email in the response for github? It crufts up the conversation a bit. If you can't, don't worry, just a thought.

**Comment by quixoft** [comment]
I will just use the web interface, sorry about missing up the thread...I can't see a way to turn it off on my mail client

**Comment by pingud98** [comment]
Hurray for collaborative working! This was beginning to read a bit like the
Linux kernel development thread ;) Glad it's sorted. As a newbie to git
I'll be trying not to mess up. Julian I will send you a trial patch just to
get the hang of it.

Off topic for Julian: (and cosimo) Also we now have the parts for a second
analogue board. We just need to assemble it. Sylvain in the electronics
workshop might help us to use the reflow machine but we'll still need to
paste (maybe by machine) and place it manually. I'll drop him a line
tomorrow!

James
