### ISSUE TITLE
Replace single quotes with double quotes in JSON output

### ISSUE THREAD

**Issue by juzsal** [CosmicPi/cosmicpi-arduino#4]
The JSON spec requires double quotes everywhere rather than single quotes. Can we replace these in the serial output?

**Comment by quixoft** [comment]
I will take a look, I am using quotes within sprintf ....  let me check

**Comment by quixoft** [comment]
There are a lot of statements like this .....

sprintf(txt,"{'barometer':{'temperature':%5.3f,'pressure':%5.3f,'altitude':%4.1f}}\n",tempb,presr,altib);

So I use the fact that a single quote doesn't terminate the string. Python doesn't care about it. So do you have any technical issues here or is it just your aesthetic sense. 
So yes I could global replace single quotes by backslash double quote in all sprintf statements if needed.

**Comment by juzsal** [comment]
Well it's just to be valid JSON, you might imagine someone writing a completely different interface to the Arduino (in a different language maybe). It'd be nice if the serial output was directly deserialisable from JSON rather than having to do a `str.replace("'", "\"")`

I guess it might make the C code ugly with all those escapes though. Whatever you think is best. It's a minor thing.

**Comment by quixoft** [comment]
Lets leave the issue open. By the way the upstream version of the arduino code is not what I want. I want what is in the main repo. I cloned that. I can clone my fork and upstream and then copy all back as is in main, or get rid of whats upstream. What is the best way to proceed ?

**Comment by juzsal** [comment]
I don't fully understand what you mean, what is it you want to do?

**Comment by quixoft** [comment]
OK if I fork and clone my fork and then do an upstream merge I get some early experimental stuff from the hackathon, not what is in CosmicPi/cosmicpi-arduino. So I just cloned CosmicPi/cosmicpi-arduino to my local computer. So I could copy everything from my copy of  CosmicPi/cosmicpi-arduino  into my fork after an upstream merge and push that. OR we can rollback the changes made in the hackathon in James's fork.

**Comment by juzsal** [comment]
From your local clone of your fork, you should do `git pull --rebase upstream master`, which will pull all the commits since you last pushed to your fork from the upstream master and into your local fork.

Does that help? You shouldn't need to physically copy any files.

[this version](https://github.com/CosmicPi/cosmicpi-arduino/blob/master/cosmicpi-arduino.ino) is the one you want, right?

**Comment by juzsal** [comment]
Basically I think you just need to sync your fork with the main repo

**Comment by quixoft** [comment]
Yes I just did it and its OK now .... I guess its me being unfamiliar with using github. Strange !

**Comment by juzsal** [comment]
Good stuff :smile:
